# Generated by Django 4.2.29 on 2026-03-25 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramplin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отрасль'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_video_url',
            field=models.URLField(blank=True, verbose_name='Видео-презентация (YouTube/Vimeo)'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_website',
            field=models.URLField(blank=True, verbose_name='Сайт компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='GitHub / GitLab'),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=20, verbose_name='Год выпуска / Курс'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='Портфолио'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Навыки (через запятую)'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=200, verbose_name='Университет'),
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('type', models.CharField(choices=[('vacancy', 'Вакансия'), ('internship', 'Стажировка'), ('event', 'Мероприятие'), ('mentorship', 'Менторская программа')], default='vacancy', max_length=20, verbose_name='Тип')),
                ('format', models.CharField(choices=[('remote', 'Удалённо'), ('hybrid', 'Гибрид'), ('office', 'Офис')], default='remote', max_length=20, verbose_name='Формат')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('closed', 'Закрыта'), ('planned', 'Запланирована')], default='active', max_length=20, verbose_name='Статус')),
                ('salary', models.CharField(blank=True, max_length=100, verbose_name='Зарплата / Вознаграждение')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Город / Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('skills_required', models.TextField(blank=True, verbose_name='Необходимые навыки (через запятую)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('reserve', 'В резерве')], default='new', max_length=20)),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tramplin.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('opportunity', 'applicant')},
            },
        ),
    ]
