# Generated by Django 5.1.15 on 2026-03-28 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramplin', '0003_user_favorite_ids_user_is_profile_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='Обложка (URL фото офиса)')),
                ('tech_stack_json', models.TextField(blank=True, default='{}', verbose_name='Технологии (JSON)')),
                ('values_json', models.TextField(blank=True, default='[]', verbose_name='Ценности (JSON)')),
                ('perks_json', models.TextField(blank=True, default='[]', verbose_name='Преимущества (JSON)')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn компании')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram-канал')),
                ('vk_url', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('office_address', models.CharField(blank=True, max_length=300, verbose_name='Адрес офиса')),
                ('founded_year', models.CharField(blank=True, max_length=10, verbose_name='Год основания')),
                ('team_size', models.CharField(blank=True, max_length=50, verbose_name='Размер команды')),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1–5)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('vacancy_tag', models.CharField(blank=True, max_length=200, verbose_name='Вакансия (опционально)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_moderated', models.BooleanField(default=True, verbose_name='Прошёл модерацию')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'author')},
            },
        ),
    ]
