# Generated by Django 5.1.15 on 2026-03-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramplin', '0004_company_profile_and_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seeker', 'Соискатель'), ('employer', 'Работодатель'), ('curator', 'Куратор')], default='seeker', max_length=20),
        ),
    ]
