# Generated by Django 5.1.15 on 2026-03-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramplin', '0005_add_curator_role_and_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
