# Generated by Django 5.1.15 on 2026-03-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramplin', '0006_add_moderation_status_to_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия (модерация)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tramplin.opportunity',),
        ),
        migrations.CreateModel(
            name='InternshipProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Стажировка',
                'verbose_name_plural': 'Стажировки (модерация)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tramplin.opportunity',),
        ),
        migrations.CreateModel(
            name='VacancyProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии (модерация)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tramplin.opportunity',),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='office_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта офиса'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='office_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота офиса'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
