# Generated by Django 5.1.15 on 2026-03-29 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramplin', '0009_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('accepted', 'Принят')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('not_applied', 'Не подавал заявку')], db_index=True, default='pending', max_length=20, verbose_name='Статус заявки')),
                ('experience_description', models.TextField(help_text='Расскажите о своём профессиональном опыте и достижениях.', verbose_name='Описание опыта')),
                ('skills_to_teach', models.TextField(help_text='Перечислите навыки и технологии, которым вы готовы обучать.', verbose_name='Навыки для передачи')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('accepted_privacy_policy', models.BooleanField(default=False, help_text='Пользователь принял Политику конфиденциальности программы менторства.', verbose_name='Политика конфиденциальности ментора принята')),
                ('accepted_terms_of_service', models.BooleanField(default=False, help_text='Пользователь принял Условия использования программы менторства.', verbose_name='Условия использования приняты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_application', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на менторство',
                'verbose_name_plural': 'Заявки на менторство',
                'ordering': ['-applied_at'],
            },
        ),
    ]
