# Generated by Django 5.1.15 on 2026-03-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramplin', '0010_add_mentor_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(db_index=True, default=False, help_text='Устанавливается автоматически при одобрении заявки на менторство.', verbose_name='Верифицированный ментор'),
        ),
    ]
