# Generated by Django 5.1.15 on 2026-03-30 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramplin', '0013_add_avatar_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility_area', models.CharField(blank=True, help_text='Например: "Web-разработка, гр. 422ISV-2"', max_length=300, verbose_name='Зона ответственности')),
                ('availability_schedule', models.CharField(blank=True, help_text='Например: "Будни, 10:00 - 18:00"', max_length=200, verbose_name='График доступности')),
                ('approved_mentors_count', models.IntegerField(default=0, verbose_name='Количество одобренных менторов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curator_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль куратора',
                'verbose_name_plural': 'Профили кураторов',
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve_mentor', 'Одобрил заявку на менторство'), ('reject_mentor', 'Отклонил заявку на менторство'), ('approve_opportunity', 'Одобрил объявление'), ('reject_opportunity', 'Отклонил объявление'), ('block_user', 'Заблокировал пользователя'), ('unblock_user', 'Разблокировал пользователя'), ('moderate_review', 'Модерировал отзыв')], max_length=50, verbose_name='Действие')),
                ('target_description', models.CharField(blank=True, max_length=300, verbose_name='Описание объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('curator', models.ForeignKey(limit_choices_to={'role': 'curator'}, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'Запись журнала модерации',
                'verbose_name_plural': 'Журнал модерации',
                'ordering': ['-created_at'],
            },
        ),
    ]
