# Generated by Django 5.1.15 on 2026-03-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramplin', '0014_add_curator_profile_and_moderation_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_by_id_val',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID заблокировавшего'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_by_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя заблокировавшего'),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован до'),
        ),
    ]
